pr-1
bohdan2704/bookstore pull request #1
Opened 2024-02-25 17:33 UTC by bohdan2704

added layers to app

2024-02-26 09:13 UTC, Rommelua requested changes

2024-02-26 09:13 UTC, Rommelua commented on src/main/java/com/example/bookshop/model/Book.java
> +    private BigDecimal price;
add constraints

2024-02-26 09:13 UTC, Rommelua commented on src/main/java/com/example/bookshop/exception/DataProcessingException.java
> +
```suggestion
```

2024-02-27 11:20 UTC, Vasul-Pankiv requested changes

2024-02-27 11:20 UTC, Vasul-Pankiv commented on src/main/java/com/example/bookshop/model/Book.java
> +    private String coverImage;
remove empty lines

2024-02-27 11:20 UTC, Vasul-Pankiv commented on src/main/java/com/example/bookshop/repository/BookRepository.java
> +public interface BookRepository {
try to use JpaRepository, so you will no longer need to create an implementation

2024-02-27 18:29 UTC, kerrrusha approved these changes

2024-02-27 18:29 UTC, kerrrusha commented on src/main/java/com/example/bookshop/exception/DataProcessingException.java
> +        super(message);
you dont used this parameter
```suggestion
        super(message, e);
```

2024-02-27 20:09 UTC, merged